spring:
  datasource:
    password: postgres
    url: jdbc:postgresql://localhost:5432/delivery?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: postgres
  jpa:
    database: POSTGRESQL
    generate-ddl: true
    hibernate:
      ddl-auto: create
#  flyway:
#    locations: classpath:db/migration

